version: '3'

services:
  db:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  php-apache:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: dockerfile-php-apache
    volumes:
      - ./:/var/www/html/
    ports:
      - "8080:80"

volumes:
  mysql:
